name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Configure Git Identity
        run: |
          git config --global user.email "khanaldavit@gmail.com"
          git config --global user.name "davitkhanal-ai"

      - name: Install Dependencies
        run: npm install

      - name: Generate Changelog
        run: npx standard-version
